### ISSUE TITLE
Helm chart for the controller

### ISSUE THREAD

**Issue by AljoschaP** [kluctl/flux-kluctl-controller#4]
### Controller

- [ ] KluctlProject
- [ ] KluctlDeployment
- [ ] KluctlMultiDeployment

### Who are you?

Aljoscha, Platform Engineer at Hellmann Worldwide Logistics

### What do you want to do?

I would like to deploy the controller using Helm and be able customize different aspects of the controller deployment via templating.

### Why do you need that?

Because its much easier to deploy it with a packet manager like helm. On top of that, its more straightforward to customize the deployment of the controller using a values.yaml instead of patching it using kustomize or write a complete new raw K8s yaml definition.

**Comment by AljoschaP** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-kluctl-controller // Should be available in values.yaml
  labels: // Should be available in values.yaml to add additional labels
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: flux-kluctl-controller
  replicas: 1 
  template:
    metadata:
      labels: // Should be available in values.yaml to add additional labels
        app: flux-kluctl-controller
      annotations: // Should be available in values.yaml
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: flux-kluctl-controller
      terminationGracePeriodSeconds: 60 // Should be available in values.yaml
      # Required for AWS IAM Role bindings
      # https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
      securityContext: // Should be available in values.yaml
        fsGroup: 1337
      containers:
      - name: manager
        image: ghcr.io/kluctl/flux-kluctl-controller
        imagePullPolicy: IfNotPresent
        securityContext: // Should be available in values.yaml 
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: RuntimeDefault

        ports:
          - containerPort: 8080
            name: http-prom
            protocol: TCP
          - containerPort: 9440
            name: healthz
            protocol: TCP
        env:
          - name: RUNTIME_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args: // Should be available in values.yaml 
          - --watch-all-namespaces
          - --log-level=info
          - --log-encoding=json
          - --enable-leader-election
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        resources: // Should be available in values.yaml 
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - name: temp
            mountPath: /tmp
      volumes:
        - name: temp
          emptyDir: {}
```
