### ISSUE TITLE
Add kluctl installation method

### ISSUE THREAD

**Issue by benedikt-bartscher** [kluctl/flux-kluctl-controller#98]
### Controller

- [ ] KluctlDeployment

### Who are you?

Benedikt, Full Stack Engineer at SENBAX

### What do you want to do?

Is there a reason why there is no installation method via kluctl? This would allow deploying all initial dependencies (flux + flux-kluctl-controller) via one kluctl command to the cluster and after that let flux-kluctl-controller continue processing Kluctl Deployments from git.

I tried this:
```
deployments:
  - git:
      url: git@github.com:kluctl/flux-kluctl-controller.git
      ref: v0.15.0
      subDir: config/install
```
in my deployment.yaml but it obviously fails because it expects a deployment.yaml instead of a kustomization.yaml

Another option would be to provide a HelmChart/HelmDeployment CR example ready to use with kluctl.

Do we even need a kustomize install example? I think we can drop this, cause everyone who wants to deploy flux-kluctl-controller probably already has kluctl installed.

### Why do you need that?

I don't need it, but i think it keeps things cleaner when everything is a kluctl deployment.
